CREATE TABLE kv2 (
    id          INT PRIMARY KEY AUTO_INCREMENT,
    created_ts  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `key`       TEXT     NOT NULL,
    `value`     TEXT     NOT NULL,
    UNIQUE (`key`)
);

